title: Login Lesson
description: Frontend for Login/Signup Lesson
owner_name: Alisha H, Sharon K, Peyton L, Tara S, Anika B
github_username: alishahussain
github_repo: "loginteach"
baseurl: "/loginteach/"
remote_theme: jekyll/minima
minima:
plugins:
- jekyll-remote-theme
future: true
